### ISSUE TITLE
Code coverage doesn't work

### ISSUE THREAD

**Issue by TrySound** [blaugold/webpack-mocha-plugin#1]
Tests are passed well, but coverage is failed
```js
...\inferno-datagrid\node_modules\remap-istanbul\lib\remap.js:214
                        Object.keys(item).forEach(function (filePath) {
                               ^

TypeError: Cannot convert undefined or null to object
    at ...\inferno-datagrid\node_modules\remap-istanbul\lib\remap.js:214:11
    at Array.forEach (native)
    at remap (...\inferno-datagrid\node_modules\remap-istanbul\lib\remap.js:213:12)
    at WebpackMochaPlugin.generateCoverageReport (...\inferno-datagrid\node_modules\webpack-mocha-plugin\web
pack-mocha-plugin.js:75:25)
    at WebpackMochaPlugin.handleResult (...\inferno-datagrid\node_modules\webpack-mocha-plugin\webpack-mocha
-plugin.js:67:22)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:719:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
error Command failed with exit code 1.
```

**Comment by TrySound** [comment]
Sorry, forget to add instrumenter
